# Generated by Django 5.2.7 on 2025-10-01 18:59

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identifiant unique')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive'), ('archived', 'archived')], default='active', max_length=100, no_check_for_status=True, verbose_name='Statut')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Métadonnées')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Exemple : 20 pour -20%', verbose_name='Pourcentage')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalogue.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
    ]
