# Generated by Django 5.2.7 on 2025-10-01 18:59

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identifiant unique')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive'), ('archived', 'archived')], default='active', max_length=100, no_check_for_status=True, verbose_name='Statut')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Métadonnées')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de l’expéditeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
            },
        ),
    ]
